version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: mysql_excel
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sales_db
      MYSQL_USER: sales_user
      MYSQL_PASSWORD: salespass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
